### ISSUE TITLE
How to get the document score?

### ISSUE THREAD

**Issue by rockallorange** [googleapis/python-language#121]
Hi, I'm trying to use Google Natural Language API to analyze text sentiment.

My source text is this :

"Bennett has signed onto a historic coalition agreement with centrist leader Yair Lapid who brought together a wide swath of political parties as part of a change coalition to oust Netanyahu, including a far left party and even for the first time in Israeli history, an Arab-Israeli party. If Israels parliament signs off on the deal in the coming days, Bennett will take the top job for the first two years of a four-year term, followed by Lapid.He will sit alongside politicians with completely opposing ideologies to his own.Bennett lies to the right even of Netanyahu in several crucial areas. He would carry into office a history of incendiary remarks about Palestinians and a well-documented ambition to annex part of the occupied West Bank."

After I called the api, the respose is:
Document sentiment score: -0.20000000298023224
Document sentiment magnitude: 0.699999988079071

Sentence text: Bennett has signed onto a historic coalition agreement with centrist leader Yair Lapid who brought together a wide swath of political parties as part of a change coalition to oust Netanyahu, including a far left party and even for the first time in Israeli history, an Arab-Israeli party.
Sentence sentiment score: -0.10000000149011612
Sentence sentiment magnitude: 0.10000000149011612

Sentence text: If Israel's parliament signs off on the deal in the coming days, Bennett will take the top job for the first two years of a four-year term, followed by Lapid.He will sit alongside politicians with completely opposing ideologies to his own.Bennett lies to the right even of Netanyahu in several crucial areas.
Sentence sentiment score: -0.4000000059604645
Sentence sentiment magnitude: 0.4000000059604645

Sentence text: He would carry into office a history of incendiary remarks about Palestinians and a well-documented ambition to annex part of the occupied West Bank.
Sentence sentiment score: -0.10000000149011612
Sentence sentiment magnitude: 0.10000000149011612

**I'm curious how to get "Document sentiment score: -0.20000000298023224" ?
Is just average the Sentence sentiment score ?**

If anyone could tell me, I will be grateful, thanks for your help.

**Comment by munkhuushmgl** [comment]
Hello @rockallorange 

this will be a good question ask on StackOverFlow

Github issues are intended for reporting bug or service related issues.


For your question, answer can be found in the docs:

https://cloud.google.com/natural-language/docs/basics#sentiment_analysis


With this note, I am closing this issue.

**Comment by rockallorange** [comment]
Hi @munkhuushmgl 

thanks for your help, I will delete it, thanls!
