### ISSUE TITLE
How to use the outputs

### ISSUE THREAD

**Issue by ShivanshuPurohit** [googleapis/python-language#123]
How exactly do I use outputs of class `'google.cloud.language_v1.types.language_service.AnalyzeEntitiesResponse'`? They are not json serializable or scriptable, but printing them looks very much like jsons. What other formats can I convert them to and how?

**Comment by busunkim96** [comment]
Hi @ShivanshuPurohit,

The messages in this library are of proto-plus type. You can serialize messages into bytes, JSON, or a python dict. Bytes or JSON can be loaded by implementations of protobuf in other languages.

https://proto-plus-python.readthedocs.io/en/latest/messages.html#serialization

Concretely for the message you are working with:

```py
from google.cloud import language_v1

# assuming response is of type `google.cloud.language_v1.types.language_service.AnalyzeEntitiesResponse`

# to bytes
print(language_v1.AnalyzeEntitiesResponse.serialize(response))

# to JSON string
print(language_v1.AnalyzeEntitiesResponse.to_json(response))

# to dict
print(language_v1.AnalyzeEntitiesResponse.to_dict(response))
```

If you only need one or two attributes, you can access them as attributes. This is what our samples generally show.

```py
print(response.language)
```

**Comment by munkhuushmgl** [comment]
Closing this issue,

Feel free to reopen if u still experiencing any other issue.
