### ISSUE TITLE
Language API Unicode Error

### ISSUE THREAD

**Issue by Brumstar** [googleapis/python-language#131]
I am using the sample code found here https://cloud.google.com/natural-language/docs/samples/language-syntax-gcs#language_syntax_gcs-python. 

I've setup the response like the following:

~~~
client = language_v1.LanguageServiceClient()

gcs_content_uri = 'gs://my-url-here.txt'

type_ = language_v1.Document.Type.PLAIN_TEXT

language = "fr"

document = {"gcs_content_uri": gcs_content_uri, "type_": type_, "language": language}

encoding_type = language_v1.EncodingType.UTF8

response = client.analyze_syntax(request = {'document': document, 'encoding_type': encoding_type})
~~~

However, the results I get back have hex representations of unicode characters (I think) in them. 

Sample response text looks like this, with accented, and potentially other unicode characters being returned in the following manner:

~~~
content: "Au coucher du soleil, le taxi nous a d\303\251pos\303\251s devant la\nplage de Santa Monica."
begin_offset: 449122

content: "Elle \303\251tait exactement comme les\nplages de Los Angeles qu\342\200\231on voit dans les \357\254\201lms, sauf qu\342\200\231elle\nsentait mauvais."
begin_offset: 449202
~~~

This looks to be a bug in the charset/encoding of the responses that are returned.

**Comment by parthea** [comment]
@munkhuushmgl Please could you take a look?

**Comment by munkhuushmgl** [comment]
Can u share your code snippet where u loop thru results from the repsonse?
@Brumstar

**Comment by Brumstar** [comment]
The loop is:

~~~
for sentence in response.sentences:
    print(sentence.text)
~~~

**Comment by Brumstar** [comment]
> I think u were posed to use the following if u r using language_syntax_gcs
> https://github.com/googleapis/python-language/blob/cc460bd068c4001e0b5fd774ca1fbf056f289be7/samples/v1/language_syntax_gcs.py#L56-L94

Well sure, I would use that code if I wanted to analyze tokens in the sentence, but I only want the sentence. It's unclear why tokens printed by themselves in the loop would display any differently than in the sentences.

**Comment by munkhuushmgl** [comment]
> > I think u were posed to use the following if u r using language_syntax_gcs
> > https://github.com/googleapis/python-language/blob/cc460bd068c4001e0b5fd774ca1fbf056f289be7/samples/v1/language_syntax_gcs.py#L56-L94
> 
> Well sure, I would use that code if I wanted to analyze tokens in the sentence, but I only want the sentence. It's unclear why tokens printed by themselves in the loop would display any differently than in the sentences.

I see, I will escalate this to the team

**Comment by munkhuushmgl** [comment]
@Brumstar Can u make sure that your python file has the following code on top?
```
# -*- coding: utf-8 -*-
```

For example :
https://github.com/googleapis/python-language/blob/cc460bd068c4001e0b5fd774ca1fbf056f289be7/samples/v1/language_syntax_gcs.py#L1-L8

**Comment by Brumstar** [comment]
I still see the same result with this header on the top.

**Comment by munkhuushmgl** [comment]
@Brumstar 
Can u share original text file used for request?

**Comment by Brumstar** [comment]
~~~
Croyez-moi, je n’ai jamais souhaité étre un sang-mélé.

Si vous lisez ces lignes parce que vous soupconnez en
étre un, vous aussi, 6coutez mon conseil : refermez ce livre
immédiatement. Prenez pour argent comptant le mensonge
que vos parents vous ont raconté sur votre naissance et
tentez de mener une vie normale.

Une vie de sang-mélé, c’est dangereux. C’est angoissant.
Et, le plus souvent, ca se termine par une mort abominable
et douloureuse.
~~~

**Comment by busunkim96** [comment]
Ah I think I know what's happening.

[Sentence](https://github.com/googleapis/python-language/blob/242aa5e997161104b760f554f69f2eecd86cd560/google/cloud/language_v1/types/language_service.py#L102-L115) has a `text` field of type [TextSpan](https://github.com/googleapis/python-language/blob/242aa5e997161104b760f554f69f2eecd86cd560/google/cloud/language_v1/types/language_service.py#L539-L552) which has a `content` field of type `str`.

I think the strange formatting is from printing the _whole_ `TextSpan` (`response.sentences[0].text`) rather than the content field (`response.sentences[0].text.content`).

@Brumstar Could you try something like this instead?
```py
for s in response.sentences:
    print(s.text.content)
```

**Comment by Brumstar** [comment]
Yes I will try that thanks

**Comment by Brumstar** [comment]
@busunkim96 this definitely fixes this issue, thank you.
