### ISSUE TITLE
classify_text samples are not yet compatible with Python 3.10 due to numpy

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-language#208]
https://github.com/googleapis/python-language/search?q=numpy

https://source.cloud.google.com/results/invocations/e21f0eb6-962c-4f49-a6bb-615a8dd2b831/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-language%2Fsamples%2Fpython3.10%2Fpresubmit/log

```
  ----------------------------------------
  ERROR: Failed building wheel for numpy
Failed to build numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
nox > Session py-3.10 failed.
```

**Comment by matthewayne** [comment]
@busunkim96 is this something you're working on?

**Comment by busunkim96** [comment]
Hi @matthewayne, this was intended to be a tracking issue so folks aren't surprised when the 3.10 samples check fails on their PR.

Some future release of `numpy` should allow this to be closed.

**Comment by leahecole** [comment]
Seems like this is now resolved - periodic builds are passing!
