### ISSUE TITLE
TypeError: analyze_entities() got an unexpected keyword argument 'request'

### ISSUE THREAD

**Issue by Grinnbob** [googleapis/python-language#60]
I'm trying this task https://github.com/googleapis/python-language/blob/master/samples/v1/language_entities_text.py 
but script returns exception: 'google.cloud.language_v1' has no attribute 'Document'.
I fixed it by 
language_v1 => 'from google.cloud.language import enums', 'from google.cloud.language import types'

But now I have next exception:
TypeError: analyze_entities() got an unexpected keyword argument 'request'.

Where I can find actual/updated example of entity extraction code using Natural Language API?

**Comment by munkhuushmgl** [comment]
@Grinnbob Did you make sure you are using the latest version of library?

**Comment by munkhuushmgl** [comment]
https://googleapis.dev/python/language/latest/UPGRADING.html#enums-and-types

**Comment by Grinnbob** [comment]
I think the problem is in library - I've installed it 

`python3 -m pip install google-cloud-language`

but code execution returns errors as if I have installed old version.. How to install latest version?

**Comment by munkhuushmgl** [comment]
Can u share your pip versions?

**Comment by munkhuushmgl** [comment]
Please make sure run the following command to make sure you have installed latest:
```
pip install -r ..[this repo]/samples/snippets/api/requirements.txt
```

**Comment by Grinnbob** [comment]
Yes, I've installed all requirements from this file and got error:
`AttributeError: module 'google.cloud.language_v1' has no attribute 'Document'`

pip version:
`pip 19.3.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)`

code I'm trying to execute:

````
from google.cloud import language_v1

from google.cloud import language

def sample_analyze_entities(text_content):
    client = language_v1.LanguageServiceClient()

    type_ = language_v1.Document.Type.PLAIN_TEXT
    language = "en"
    document = {"content": text_content, "type_": type_, "language": language}
    #document = language_v1.Document(content=text, type_=language_v1.Document.Type.PLAIN_TEXT)

    encoding_type = language_v1.EncodingType.UTF8

    response = client.analyze_entities(request = {'document': document, 'encoding_type': encoding_type})

    for entity in response.entities:
        print(u"Representative name for the entity: {}".format(entity.name))

        print(u"Entity type: {}".format(enums.Entity.Type(entity.type_).name))

        print(u"Salience score: {}".format(entity.salience))

        for metadata_name, metadata_value in entity.metadata.items():
            print(u"{}: {}".format(metadata_name, metadata_value))

        # Loop over the mentions of this entity in the input document.
        # The API currently supports proper noun mentions.
        for mention in entity.mentions:
            print(u"Mention text: {}".format(mention.text.content))

            # Get the mention type, e.g. PROPER for proper noun
            print(
                u"Mention type: {}".format(language_v1.EntityMention.Type(mention.type_).name)
            )

    print(u"Language of the text: {}".format(response.language))

sample_analyze_entities("California is a state.")
````

**Comment by munkhuushmgl** [comment]
Share this info please 

(1) Python version. python --version

(2) OS

(3) Open SSL version. python -c "import ssl; print ssl.OPENSSL_VERSION"

(4) Versions of the following packages. (A full pip freeze is also fine.)

google-cloud-language
google-api-core

**Comment by Grinnbob** [comment]
(1) Python 3.6.9
(2) linux
(3) OpenSSL 1.1.1  11 Sep 2018
(4) google-cloud-language==1.2.0
     google-api-core==1.16.0

(I execute it in Google Colab)

**Comment by munkhuushmgl** [comment]
(4)  google-cloud-language==1.2.0
4 should be:
(4)  google-cloud-language==2.0.0

**Comment by munkhuushmgl** [comment]
https://github.com/googleapis/python-language/releases/tag/v2.0.0

**Comment by Grinnbob** [comment]
Thanks!
